"""The ``market`` family's ``auction`` mode: what an auction expands into — bidder and seller props, the lot's world
props, the bid, ask, open, close and tick actions, a bidding stage (or hooks into a declared one), the results record,
views, outputs and the escrow invariant — all backed by the native lots and clearing in :mod:`.auctions`."""
from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any

from ..errors import RunError
from ..registry import MechanismError, family_action, mode
from ._common import conserve_invariant, declared_entity, entity_of, fmt, stage_event
from ._social import check_expr
from .auctions import FORMATS, MIN_PRICE, SEALED, AuctionConfig, bid, close_sealed, open_lot, tick
from .econ_base import money_prop
from .package_auction import MAX_PACKAGE_ITEMS


def _format_check(action: str) -> Callable[[Any, dict[str, Any], str], list[tuple[str, str, str | None]]]:
    """Check-time: a bid or ask names only what the auction's format takes."""

    def check(checker: Any, effect: dict[str, Any], path: str) -> list[tuple[str, str, str | None]]:
        raw = (getattr(checker.c, "mechanisms", None) or {}).get(effect.get("market"))
        chosen = raw.get("format") if isinstance(raw, Mapping) else None
        if chosen not in FORMATS:
            return []
        where = f"a {chosen} auction"
        if action == "ask" and chosen != "double":
            return [(f"{path}.action", f"{where} takes no asks", "only a double auction takes asks; use action bid")]
        if chosen == "combinatorial":
            if "package" not in effect:
                return [(path, f"`market.bid` on {where} needs `package`", "list the items bid on together")]
            if "qty" in effect:
                return [(f"{path}.qty", f"{where} takes `package`, not `qty`", "remove qty")]
        elif "package" in effect:
            return [(f"{path}.package", f"`package` belongs to a combinatorial auction, not {where}", "remove package")]
        return []

    return check


#: action → (its keys, the required ones, generated by the mechanism itself, example keys, what it does).
#: `who` is the bidder (default $actor); receipts land in $world.<name>_receipt.
_ACTIONS: dict[str, tuple[tuple[str, ...], tuple[str, ...], bool, str, str]] = {
    "bid": (("who", "price", "qty", "package"), ("price",), False, '"price": 120',
            "bid on the open lot; `qty` for uniform and double, `package` lists the items of a combinatorial bid"),
    "ask": (("who", "price", "qty"), ("price",), False, '"price": 90, "qty": 1', "offer units in a double auction"),
    "open": ((), (), True, "", "open a lot when there is something to sell"),
    "close": ((), (), True, "", "clear a sealed lot"),
    "tick": ((), (), True, "", "move the English or Dutch clock"),
}


def _runner(action: str) -> Callable[[Any, dict[str, Any], dict[str, Any], str], None]:
    def run(runner: Any, effect: dict[str, Any], vars: dict[str, Any], where: str) -> None:
        world = runner.world
        name = effect["market"]
        try:
            if action == "open":
                open_lot(world, name)
            elif action == "close":
                close_sealed(world, name)
            elif action == "tick":
                tick(world, name)
            else:
                trader = entity_of(world, runner.eval(effect.get("who", "$actor"), vars), f"{where}.who", "a bidder")
                bid(world, name, trader, action, runner.eval(effect["price"], vars),
                    runner.eval(effect.get("qty", 1), vars), runner.eval(effect.get("package"), vars))
        except RunError as exc:
            raise RunError(str(exc), where) from None

    return run


def _register_actions() -> None:
    for action, (keys, required, internal, fields, doc) in _ACTIONS.items():
        example = '{"market": "house", "action": "' + action + '"' + (f", {fields}" if fields else "") + f"}}  ({doc})"
        family_action("market", ("auction",), action, keys=keys, required=required, internal=internal, example=example,
                      check=_format_check(action) if action in ("bid", "ask") else None)(_runner(action))


_register_actions()


def _party_props(name: str, cfg: AuctionConfig, contract: Mapping[str, Any], holder: str) -> dict[str, Any]:
    props = {**money_prop(contract, holder, cfg.currency),
             f"{name}_units": {"type": "int", "default": 0, "description": f"Units of {cfg.item} held."},
             f"{name}_escrow": {"type": "number", "default": 0, "private": True,
                                "description": "Cash held for open bids."},
             f"{name}_escrow_units": {"type": "int", "default": 0, "private": True},
             f"{name}_won": {"type": "int", "default": 0}}
    if cfg.format == "combinatorial":
        props[f"{name}_items"] = {"type": "list", "default": [], "description": "Items won."}
    return props


def _check_award(name: str, cfg: AuctionConfig) -> None:
    """A tender needs a house that buys and pays, and a most-it-pays reserve; a score ranks first-price bids; a house
    sells the units it holds, so a `stock` beside it would be ignored."""
    if cfg.reverse:
        if cfg.format not in ("first_price", "second_price"):
            raise MechanismError(f"a reverse auction is sealed: format first_price or second_price, not {cfg.format}",
                                 "set format: first_price (winner is paid its offer) or second_price", "format")
        if not cfg.house:
            raise MechanismError("a reverse auction needs `house`: the entity that buys and pays the winner",
                                 'e.g. "house": "city" (an entity with cash)', "house")
        if not isinstance(cfg.reserve, str) and cfg.reserve <= 0:
            raise MechanismError("a reverse auction needs `reserve`: the most the house pays per unit",
                                 'e.g. "reserve": 500', "reserve")
    if cfg.deliver_from and not cfg.reverse:
        raise MechanismError("`deliver_from` belongs to a tender: the winner's stock supplies the house",
                             "set reverse: true, or remove deliver_from", "deliver_from")
    if cfg.house and not cfg.reverse and "stock" in cfg.model_fields_set and cfg.format != "double":
        raise MechanismError(f"`stock` is not used with a house: house '{cfg.house}' sells the units it holds in "
                             f"`{name}_units`", f"remove stock and give the house its units under "
                             f"entities.{cfg.house}.props, e.g. \"{name}_units\": 3", "stock")
    if cfg.score is not None:
        if cfg.format != "first_price":
            raise MechanismError("a scored award pays the winner its own bid, so it needs format first_price, not "
                                 f"{cfg.format}",
                                 "set format: first_price", "score")
        check_expr(cfg.score, "score", ["it", "price"])


def _check_packages(cfg: AuctionConfig) -> None:
    if cfg.format != "combinatorial":
        if cfg.items or cfg.reserves:
            raise MechanismError("`items` and `reserves` belong to a combinatorial auction",
                                 "set format: combinatorial", "items")
        return
    if not cfg.items:
        raise MechanismError("a combinatorial auction needs `items`: the distinct things sold in packages",
                             'e.g. "items": ["north", "south", "east"]', "items")
    if len(set(cfg.items)) != len(cfg.items) or not all(item.strip() for item in cfg.items):
        raise MechanismError("`items` must be distinct, non-empty names", None, "items")
    if len(cfg.items) > MAX_PACKAGE_ITEMS:
        raise MechanismError(f"a combinatorial auction sells at most {MAX_PACKAGE_ITEMS} items at once (exact winner "
                             "determination)", "split the items across lots or auctions", "items")
    unknown = sorted(set(cfg.reserves) - set(cfg.items))
    if unknown:
        raise MechanismError(f"reserves name items that are not for sale: {', '.join(unknown)}",
                             f"items: {', '.join(cfg.items)}", "reserves")


@mode("market", "auction", AuctionConfig,
           "An auction: sealed first_price, second_price (Vickrey), english (ascending, increment, timeout), dutch "
           "(falling clock), double (call market at one price) or uniform (multi-unit, one price). Tools `<name>_bid` "
           "(price, qty) and, for double, `<name>_ask`. Each party holds the units it bought, or a double auction's "
           "sellers the units they offer, in `<name>_units` (give sellers their stock there). Bids escrow cash, asks "
           "escrow units; proceeds go to the `house` entity or $world.<name>_proceeds, and $world.<name>_revenue "
           "counts what every sale paid (a tender's: what the house paid; a double auction's: what buyers paid "
           "sellers). `reverse: true` makes it a procurement tender (the house buys; the lowest offer at or below "
           "the reserve wins, is paid and supplies one unit to the house's `<name>_units`, taken from its "
           "`deliver_from` stock when set); `score` awards a first_price lot to the best score instead of the best "
           "price. Each closed lot is posted to the `<name>_results` record, one entry per winner (winner, price, qty,"
           " lot, note; an unsold lot has one entry with winner ''). $auction(<name>).last is the latest closed lot, "
           "sold or not: {lot, winner (the first winner, '' when unsold), winners, price (the first winner's price per"
           " unit; in a uniform auction every winner pays it), qty (units sold), note}, null before the first lot "
           "closes; output `<name>_prices` lists the price of every winning entry. The other fields of $auction(name) "
           "describe the open lot; $auction_text(name, viewer) describes it.",
           example={"format": "second_price", "who": "collector", "item": "a painting", "stock": 3, "reserve": 50},
           context={"types": {"collector": {"agent": True, "props": {"cash": 500}}}})
def _expand_auction(name: str, cfg: AuctionConfig, contract: Mapping[str, Any]) -> dict[str, Any]:
    types = contract.get("types") or {}
    for field, kind in (("who", cfg.who), ("sellers", cfg.sellers)):
        if kind is not None and kind not in types:
            raise MechanismError(f"{field} '{kind}' is not a declared type", f"types: {', '.join(types) or 'none'}",
                                 field)
    if cfg.format == "dutch" and cfg.start_price is None:
        raise MechanismError("a dutch auction needs `start_price`", None, "start_price")
    if cfg.format not in ("uniform", "double") and cfg.units != 1:
        raise MechanismError("only uniform and double auctions trade several units at once", "set units: 1", "units")
    _check_packages(cfg)
    _check_award(name, cfg)
    stocked = (types[cfg.who].get("props") or {}) if isinstance(types[cfg.who], Mapping) else {}
    if cfg.deliver_from and cfg.deliver_from not in stocked:
        raise MechanismError(f"deliver_from '{cfg.deliver_from}' is not a property of {cfg.who}",
                             f"declare it under types.{cfg.who}.props (the stock each bidder can supply)",
                             "deliver_from")
    packaged = cfg.format == "combinatorial"
    party_types = {cfg.who: {"props": _party_props(name, cfg, contract, cfg.who)}}
    if cfg.format == "double":
        party_types[cfg.sellers or cfg.who] = {"props": _party_props(name, cfg, contract, cfg.sellers or cfg.who)}
    if cfg.house:
        entity = declared_entity(contract, cfg.house, "house", "house")
        if entity.get("type") not in types:
            raise MechanismError(f"house '{cfg.house}' is not of a declared type", "declare its type", "house")
        party_types[entity["type"]] = {"props": _party_props(name, cfg, contract, entity["type"])}
    sealed = cfg.format in SEALED
    single = cfg.format not in ("uniform", "double")
    receipt = f"{{$world.{name}_receipt}}"
    rules = {"first_price": "Sealed bids; the highest bid at or above the reserve wins and pays its bid.",
             "second_price": "Sealed bids; the highest bid wins and pays the second-highest bid (or the reserve), so "
                             "bidding your true value is safe.",
             "reverse_first_price": "Sealed offers to supply the house; the lowest offer at or below the reserve (the "
                                    "most the house pays) wins and is paid its offer.",
             "reverse_second_price": "Sealed offers to supply the house; the lowest offer at or below the reserve "
                                     "wins and is paid the second-lowest offer (or the reserve), so offering your "
                                     "true cost is safe.",
             "english": f"Open bids; beat the high bid by at least {fmt(cfg.increment, 4)}. The lot closes after "
                        f"{cfg.timeout} round(s) without a new bid; the winner pays its bid.",
             "dutch": "The clock price falls every round; the first bid at or above it takes the lot at the clock "
                      "price.",
             "double": "Sealed bids to buy and asks to sell, cleared together at one market-clearing price (the middle "
                       "of the range that clears).",
             "uniform": f"Sealed bids for up to {cfg.units} units; the highest bids win and all pay one clearing "
                        "price.",
             "combinatorial": f"Sealed bids on packages of {', '.join(cfg.items)}: bid on up to {cfg.packages} "
                              "packages; you win at most one of them and each item goes to one winner, chosen to "
                              "raise the most over the reserves. "
                              + ("Winners pay only the value their win takes from the other bidders, so bidding what "
                                 "a package is worth to you is safe." if cfg.payment == "vcg"
                                 else "Winners pay their bids.")}[
        f"reverse_{cfg.format}" if cfg.reverse else cfg.format]
    if cfg.score is not None:
        rules = ("Sealed offers to supply the house; among offers at or below the reserve, the best score wins and is "
                 "paid " if cfg.reverse else
                 "Sealed bids; among bids at or above the reserve, the best score wins and pays ") + \
            f"its own price. Score: {cfg.score} ($price is your price, $it you)."
    escrow = (" Your highest package bid is held until the lot closes; you get back whatever you do not pay."
              if packaged else
              " Nothing is held: when the lot closes the house pays the winner, who supplies one unit"
              + (f" from its {cfg.deliver_from} (you need one in stock to offer)." if cfg.deliver_from else ".")
              if cfg.reverse else
              " Your bid's full amount is held until the lot closes; you get back whatever you do not pay.")
    amount = {"qty": {"type": "int", "min": 1, "max": 1 if single else cfg.units, "default": 1,
                      "description": "Units wanted."}}
    if packaged:
        amount = {"package": {"type": "list", "items": {"type": "enum", "values": cfg.items}, "min_items": 1,
                              "max_items": len(cfg.items), "description": "The items you want together."}}
    price: dict[str, Any] = {"type": "number", "min": f"$auction({name}).min_bid",
                             "max": f"$actor.{cfg.currency} + $actor.{name}_escrow" if packaged
                             else f"$actor.{cfg.currency}",
                             "description": "Price for the whole package." if packaged else "Price per unit."}
    when = [{"expr": f"$auction({name}).open", "why": "No lot is open."},
            {"expr": f"$actor.{cfg.currency} > 0", "why": f"You have no {cfg.currency}."}]
    if cfg.reverse:
        price = {"type": "number", "min": MIN_PRICE, "max": f"$auction({name}).reserve",
                 "description": "Price per unit you want to be paid."}
        when = when[:1]
        if cfg.deliver_from:
            when.append({"expr": f"$actor.{cfg.deliver_from} >= 1", "why": f"You have no {cfg.item} in stock."})
    actions: dict[str, Any] = {
        f"{name}_bid": {
            "by": cfg.who,
            "description": f"{'Offer to supply' if cfg.reverse else 'Bid for'} {cfg.item}. {rules}{escrow}",
            "params": {**amount, "price": price}, "when": when,
            "do": [{"market": name, "action": "bid", "price": "$params.price",
                    **({"package": "$params.package"} if packaged else {"qty": "$params.qty"})}],
            # a sealed bid ends the turn on the auction's own stage; on a declared stage the turn's budget, shared
            # with the other mechanisms there, decides (the bidder may still trade elsewhere)
            "outcome": receipt, "private": sealed, "terminal": sealed and not packaged and cfg.stage is None,
        },
    }
    if cfg.format == "english":
        actions[f"{name}_bid"]["when"].append({"expr": f"$auction({name}).leader != $actor.id",
                                               "why": "You hold the high bid."})
    if cfg.format == "double":
        actions[f"{name}_ask"] = {
            "by": cfg.sellers or cfg.who,
            "description": f"Offer {cfg.item} for sale. {rules} Your units are held until the lot closes.",
            "params": {"price": {"type": "number", "min": MIN_PRICE,
                                 "description": "Lowest price per unit you accept."},
                       "qty": {"type": "int", "min": 1, "max": f"$min($actor.{name}_units, {cfg.units})", "default": 1,
                               "description": "Units offered."}},
            "when": [{"expr": f"$auction({name}).open", "why": "No lot is open."},
                     {"expr": f"$actor.{name}_units > 0", "why": "You have nothing to sell."}],
            "do": [{"market": name, "action": "ask", "price": "$params.price", "qty": "$params.qty"}],
            "outcome": receipt, "private": True, "terminal": True,
        }
    winner_text = ("{$entity($it.winner).name if $it.winner else 'unsold'}" +
                   ("{$' won ' + $join($it.items, ' + ') + ' for ' + $fmt($it.price, 'money') if $it.winner else ''}"
                    if packaged else
                    "{$' × ' + $text($it.qty) + ' at ' + $fmt($it.price, 'money') if $it.winner else ''}"))
    fragment: dict[str, Any] = {
        "types": party_types,
        "world": {f"{name}_lot": {"type": "map", "default": {}}, f"{name}_seq": {"type": "int", "default": 0},
                  **({f"{name}_items": {"type": "list", "default": list(cfg.items),
                                        "description": "Items still for sale."}}
                     if packaged else {}),
                  f"{name}_revenue": {"type": "number", "default": 0,
                                      "description": "What the sales paid in all: a report, holding no money."},
                  **({} if cfg.house else {f"{name}_proceeds": {"type": "number", "default": 0,
                                                                "description": "The money the sales paid, held by the "
                                                                               "auction (it has no `house`)."}}),
                  f"{name}_stock": {"type": "int", "default": len(cfg.items) if packaged else
                                    0 if (cfg.house and not cfg.reverse) or cfg.format == "double" else cfg.stock,
                                    "description": "Units the house still has to sell."},
                  f"{name}_sold": {"type": "int", "default": 0},
                  f"{name}_receipt": {"type": "text", "default": ""}},
        "records": {f"{name}_results": {"fields": {"lot": "int", "winner": "text", "price": "number", "qty": "int",
                                                   "note": "text", **({"items": "list"} if packaged else {})},
                                        "show": f"Lot {{lot}}: {winner_text} ({{note}})",
                                        "description": "Closed lots."}},
        "actions": actions,
        "events": [{"name": f"{name}_open", "phase": "start", "do": [{"market": name, "action": "open"}]}],
        "views": {f"{name}_lot": {"for": sorted({cfg.who, cfg.sellers or cfg.who}),
                                  "show": f"{{$auction_text({name}, $actor)}}"},
                  f"{name}_recent": {"for": sorted({cfg.who, cfg.sellers or cfg.who}), "title": "Recent results",
                                     "of": f"$reverse($slice($records({name}_results), -3))",
                                     "show": f"Lot {{lot}}: {winner_text}"}},
        "metrics": {f"{name}_sold": f"$world.{name}_sold", f"{name}_revenue": f"$world.{name}_revenue"},
        "outputs": {f"{name}_sold": {"expr": f"$world.{name}_sold", "type": "int", "description": "Units sold."},
                    f"{name}_revenue": {"expr": f"$world.{name}_revenue", "type": "number",
                                        "description": "What the sales paid in all (a tender: what the house "
                                                       "paid; a double auction: what buyers paid sellers)."},
                    f"{name}_prices": {"expr": f"$map($filter($records({name}_results), $it.winner != ''), $it.price)",
                                       "type": "list",
                                       "description": "Price per unit of each winning entry (one per winner of a "
                                                      "lot)."}},
    }
    names = list(actions)
    if not sealed:
        fragment["events"].append({"name": f"{name}_tick", "phase": "end", "do": [{"market": name, "action": "tick"}]})
    if cfg.stage is None:
        stage: dict[str, Any] = {"name": name, "turns": "simultaneous" if sealed else "sequential", "actions": names,
                                 "when": f"$auction({name}).open", "brief": f"{rules}"}
        if not sealed:
            stage["order"] = "random"
        if packaged:
            stage.update(max_actions=cfg.packages, max_calls=cfg.packages + 4)
        fragment["stages"] = [stage]
    else:
        hook: dict[str, Any] = {"actions": names}
        if packaged:
            hook["max_actions"] = cfg.packages
        fragment["stage_hooks"] = {cfg.stage: hook}
    if sealed:
        fragment["events"].append(stage_event(cfg.stage or name, "end", [{"market": name, "action": "close"}]))
    invariants = conserve_invariant(cfg.conserve, f"$auction_ok({name})",
                                    f"The {name} auction's escrow matches its open bids and every item is held once.")
    if invariants:
        fragment["invariants"] = invariants
    return fragment
