"""The order book's expression functions ($book, $book_depth, $book_orders, $book_account, $book_ok) and the
actions of the ``market`` effect op for the ``order_book`` mode."""
from __future__ import annotations

from collections.abc import Callable
from typing import Any

from ..errors import RunError
from ..expr import Call, ExprError, function
from ..expr.objects import Entity
from ..registry import family_action
from ._common import entity_of
from .book_session import close_round, open_round
from .order_book import account, audit, book_config, cancel, cancel_all, depth, place, quote

__all__: list[str] = []


def _name(call: Call) -> str:
    name = call.arg(0)
    try:
        book_config(call.scope.world, name)
    except RunError as exc:
        raise ExprError(f"${call.name}: {exc.message if hasattr(exc, 'message') else exc}", call.source) from None
    return str(name)


def _trader(call: Call, index: int) -> Entity:
    value = call.arg(index)
    found = call.scope.world.entity(value)
    if found is None:
        raise ExprError(f"${call.name}: expected a trader, got {value!r}", call.source)
    return found


@function("book(name)", "Top of an order book: {last, bid, ask, mid, spread, bid_qty, ask_qty, ref, halted, "
          "halt_until, open, high, low, round_volume, round_trades, volume, vwap, trades, fees, halts, orders, flow, "
          "liquidations, bar, bar_rounds, tick, lot, maker_fee_bps, taker_fee_bps, short_limit, halt_pct, band_low, "
          "band_high, heat}; flow is the last round's aggressive {buy, sell} quantity by trader kind; bar is the bar "
          "in progress {bar, open, high, low, close, volume, vwap, trades, halted, flow, ends}; heat is recent "
          "volatility against the usual (1 = as usual, 0.5–2), which coded traders other than market makers multiply "
          "their activity by.", min_args=1, max_args=1)
def _book_function(call: Call) -> dict[str, Any]:
    return quote(call.scope.world, _name(call))


@function("book_depth(name, levels?, viewer?)", "Order book price levels as a ladder (asks high→low, then bids "
          "high→low): [{side, price, qty, orders, mine}]; `mine` is the viewer's own quantity.", min_args=1, max_args=3)
def _depth_function(call: Call) -> list[dict[str, Any]]:
    name = _name(call)
    levels = call.arg(1)
    if levels is not None and (isinstance(levels, bool) or not isinstance(levels, int) or levels < 1):
        raise ExprError(f"$book_depth: levels must be a whole number ≥ 1, got {levels!r}", call.source)
    return depth(call.scope.world, name, levels, _trader(call, 2) if len(call) > 2 else None)


@function("book_orders(name, trader)",
          "A trader's resting orders, best price first: [{id, side, price, qty, seq, round}].", min_args=2, max_args=2)
def _orders_function(call: Call) -> list[dict[str, Any]]:
    name, trader = _name(call), _trader(call, 1)
    world: Any = call.scope.world
    return [dict(o) for side in ("bids", "asks") for o in world.props.get(f"{name}_{side}") or [] if o["owner"]
            == trader.id]


@function("book_account(name, trader)", "A trader's account on a book: {cash, shares, reserved_cash, reserved_shares, "
          "position, equity, pnl, fees_paid, orders, max_buy, max_sell}.", min_args=2, max_args=2)
def _account_function(call: Call) -> dict[str, Any]:
    return account(call.scope.world, _name(call), _trader(call, 1))


@function("book_ok(name)", "True while the book's accounting holds: reserves equal resting orders, balances within "
          "limits, the book in price-time order and never crossed.", min_args=1, max_args=1)
def _ok_function(call: Call) -> bool:
    return not audit(call.scope.world, _name(call))


#: action → (its keys, the required ones, generated by the mechanism itself, example keys, what it does).
#: `who` is the trader (default $actor); receipts land in $world.<name>_receipt.
_ACTIONS: dict[str, tuple[tuple[str, ...], tuple[str, ...], bool, str, str]] = {
    "buy": (("who", "qty", "price"), ("qty",), False, '"qty": 10, "price": 50.5',
            "a limit buy with a price, a market buy without"),
    "sell": (("who", "qty", "price"), ("qty",), False, '"qty": 10', "a limit sell with a price, a market sell without"),
    "cancel": (("who", "order"), ("order",), False, '"order": "$params.order"', "cancel one resting order by id"),
    "cancel_all": (("who",), (), False, "", "cancel every resting order of the trader"),
    "algo": (("who",), (), False, "", "let the trader's coded strategy act once"),
    "open": ((), (), False, "", "open the round (once a round; the book's own start event runs it after yours): expire "
                                "orders, resume after a halt, start a bar, reset the round"),
    "close": ((), (), False, "", "close the round (once a round; the book's own end event runs it after yours, so run "
                                 "it first in an end event that reads the closed round or bar): breaker check, record "
                                 "the bar"),
}


def _runner(action: str) -> Callable[[Any, dict[str, Any], dict[str, Any], str], None]:
    def run(runner: Any, effect: dict[str, Any], vars: dict[str, Any], where: str) -> None:
        world = runner.world
        name = effect["market"]
        try:
            if action == "open":
                open_round(world, name)
            elif action == "close":
                close_round(world, name)
            else:
                trader = entity_of(world, runner.eval(effect.get("who", "$actor"), vars), f"{where}.who", "a trader")
                if action in ("buy", "sell"):
                    place(world, name, trader, action, runner.eval(effect["qty"], vars),
                          runner.eval(effect.get("price"), vars))
                elif action == "cancel":
                    cancel(world, name, trader, runner.eval(effect["order"], vars))
                elif action == "cancel_all":
                    cancel_all(world, name, trader)
                else:
                    from .traders import run_algo

                    run_algo(world, name, trader)
        except RunError as exc:
            raise RunError(str(exc), where) from None

    return run


def _register_actions() -> None:
    for action, (keys, required, internal, fields, doc) in _ACTIONS.items():
        example = '{"market": "acme", "action": "' + action + '"' + (f", {fields}" if fields else "") + f"}}  ({doc})"
        family_action("market", ("order_book",), action, keys=keys, required=required, internal=internal,
                      example=example)(_runner(action))


_register_actions()
