"""Extension points: mechanism families, their modes, and effect operations.

A **family** groups mechanisms that do the same kind of job (``market``, ``economy``, ``decision`` …).
Each family has **modes**, one per variant (``market`` → ``order_book``, ``auction`` …); a mode has its own
strict config model and expands into ordinary contract sections::

    "mechanisms": {"house": {"kind": "market", "mode": "auction", "format": "english", ...}}

A family has ONE effect op, keyed by the family's name, whose value is always the name of a declared
mechanism of that family and whose ``action`` says what to do::

    {"market": "house", "action": "bid", "who": "$actor", "price": 120}

Each action registers its own keys, so an effect is checked against exactly what its action takes.
Everything registered works only through the world's journaled API, so atomic rollback, snapshots and
determinism hold for it. New mechanisms are added as modes of a family, never as new kinds.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from difflib import get_close_matches
from typing import Any, Callable, Dict, List, Mapping, Optional, Tuple, Type

from pydantic import BaseModel

__all__ = [
    "OpSpec", "ModeSpec", "FamilySpec", "MechanismSpec", "MechanismError", "OPS", "FAMILIES", "MECHANISMS",
    "RENAMED_KINDS", "RENAMED_OPS", "effect_op", "family", "mode", "mechanism", "family_action", "use_key", "config_data",
    "uses_of", "describe", "renamed_op_hint", "Issue3",
]

#: ``(path suffix, message, fix)`` — a problem an op selection or check reports.
Issue3 = Tuple[str, str, Optional[str]]


@dataclass(frozen=True)
class OpSpec:
    """A native effect operation (a family op, or one action of a family op)."""

    name: str
    #: Every key the op accepts; the op's own name is always accepted.
    keys: Tuple[str, ...]
    #: ``run(runner, effect, vars, where)`` — change the world through ``runner.world``.
    run: Callable[[Any, Dict[str, Any], Dict[str, Any], str], None]
    example: str
    required: Tuple[str, ...] = ()
    #: Keys holding plain names (not expressions), skipped by the expression checker.
    literal: Tuple[str, ...] = ()
    #: Keys holding templates rather than expressions.
    templates: Tuple[str, ...] = ()
    #: Extra static checks: ``check(checker, effect, path)`` returning ``[(path, message, fix), ...]``.
    check: Optional[Callable[[Any, Dict[str, Any], str], list]] = None
    #: Keys whose values name locals the op sets (like ``as``); later effects and templates can read them.
    binds: Tuple[str, ...] = ()
    #: Generated by mechanisms for their own bookkeeping (ticks, setup): works, but is not documented.
    internal: bool = False
    #: A family op: ``select(effect, mechanisms)`` → the chosen action's spec, or a problem.
    select: Optional[Callable[[Mapping[str, Any], Mapping[str, Any]], Tuple[Optional["OpSpec"], Optional[Issue3]]]] = None


@dataclass(frozen=True)
class ModeSpec:
    """One mode of a family: validated config in, contract sections out."""

    family: str
    mode: str
    doc: str
    config: Type[BaseModel]
    #: ``expand(use_name, config, contract_so_far)`` → a fragment of contract sections.
    expand: Callable[[str, Any, Mapping[str, Any]], Dict[str, Any]]
    example: Dict[str, Any] = field(default_factory=dict)

    @property
    def key(self) -> str:
        """``family.mode`` — how code refers to this mode."""
        return f"{self.family}.{self.mode}"


@dataclass
class FamilySpec:
    """A family of mechanisms: its modes and the actions of its effect op, per mode."""

    name: str
    doc: str
    #: Fields every mode names the same way, with what they mean (documentation).
    shared: Dict[str, str] = field(default_factory=dict)
    modes: Dict[str, ModeSpec] = field(default_factory=dict)
    #: mode → action → spec.
    actions: Dict[str, Dict[str, OpSpec]] = field(default_factory=dict)


@dataclass(frozen=True)
class MechanismSpec:
    """A mechanism kind registered outside the families (being moved into a family)."""

    kind: str
    doc: str
    config: Type[BaseModel]
    expand: Callable[[str, Any, Mapping[str, Any]], Dict[str, Any]]
    example: Dict[str, Any] = field(default_factory=dict)


class MechanismError(Exception):
    """A mechanism's config cannot be expanded; the message says what to fix."""

    def __init__(self, message: str, fix: Optional[str] = None, path: str = ""):
        super().__init__(message)
        self.fix = fix
        self.path = path


OPS: Dict[str, OpSpec] = {}
FAMILIES: Dict[str, FamilySpec] = {}
MECHANISMS: Dict[str, MechanismSpec] = {}
#: A kind name that became a family mode → (family, mode), for a clear error.
RENAMED_KINDS: Dict[str, Tuple[str, str]] = {}
#: An effect op that became a family action → (family, action), for a clear error.
RENAMED_OPS: Dict[str, Tuple[str, str]] = {}

#: Keys of a mechanism entry that choose what it is (never part of a mode's config).
_SWITCH = ("kind", "mode")


# ---------------------------------------------------------------------------
# Reading declared mechanisms
# ---------------------------------------------------------------------------


def use_key(raw: Any) -> Optional[str]:
    """What a declared mechanism is: ``family.mode`` (or a kind still outside the families); None if unreadable."""
    if not isinstance(raw, Mapping):
        return None
    kind = raw.get("kind")
    if not isinstance(kind, str):
        return None
    if kind in FAMILIES:
        mode = raw.get("mode")
        return f"{kind}.{mode}" if isinstance(mode, str) else None
    return kind


def config_data(raw: Mapping[str, Any]) -> Dict[str, Any]:
    """A declared mechanism's config fields, without ``kind`` (and ``mode`` for a family's mechanism)."""
    drop = _SWITCH if raw.get("kind") in FAMILIES else ("kind",)
    return {key: value for key, value in raw.items() if key not in drop}


def uses_of(mechanisms: Optional[Mapping[str, Any]], key: str) -> Dict[str, Mapping[str, Any]]:
    """Every declared mechanism that is ``key`` (``family.mode``, or a family for any of its modes): {name: raw}."""
    out: Dict[str, Mapping[str, Any]] = {}
    for name, raw in (mechanisms or {}).items():
        found = use_key(raw)
        if found is not None and (found == key or ("." not in key and found.split(".", 1)[0] == key)):
            out[name] = raw
    return out


def describe(key: str) -> str:
    """``key`` in words for messages: ``market (auction)``."""
    family_name, _, mode = key.partition(".")
    return f"{family_name} ({mode})" if mode else key


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------


def effect_op(name: str, keys: Tuple[str, ...], example: str, *, required: Tuple[str, ...] = (),
              literal: Tuple[str, ...] = (), templates: Tuple[str, ...] = (),
              check: Optional[Callable[[Any, Dict[str, Any], str], list]] = None,
              binds: Tuple[str, ...] = ()) -> Callable[[Callable[..., None]], Callable[..., None]]:
    """Register a native effect operation outside the families (being moved into a family)."""

    def register(run: Callable[..., None]) -> Callable[..., None]:
        if name in OPS:
            raise ValueError(f"effect op '{name}' is registered twice")
        declared = (name, *keys, *[key for key in binds if key not in keys])
        OPS[name] = OpSpec(name, declared, run, example, required, literal, templates, check, tuple(binds))
        return run

    return register


def family(name: str, doc: str, shared: Optional[Mapping[str, str]] = None) -> FamilySpec:
    """Register a family of mechanisms (once, before its modes)."""
    if name in FAMILIES:
        raise ValueError(f"mechanism family '{name}' is registered twice")
    spec = FamilySpec(name, doc, dict(shared or {}))
    FAMILIES[name] = spec
    return spec


def mechanism(kind: str, config: Type[BaseModel], doc: str,
              example: Optional[Dict[str, Any]] = None) -> Callable[[Callable[..., Dict[str, Any]]], Callable[..., Dict[str, Any]]]:
    """Register a mechanism kind outside the families (while the remaining kinds move into theirs)."""

    def register(expand: Callable[..., Dict[str, Any]]) -> Callable[..., Dict[str, Any]]:
        if kind in MECHANISMS or kind in FAMILIES:
            raise ValueError(f"mechanism kind '{kind}' is registered twice")
        MECHANISMS[kind] = MechanismSpec(kind, doc, config, expand, dict(example or {}))
        return expand

    return register


def mode(family_name: str, mode: str, config: Type[BaseModel], doc: str, example: Optional[Dict[str, Any]] = None, *,
         was: Optional[str] = None) -> Callable[[Callable[..., Dict[str, Any]]], Callable[..., Dict[str, Any]]]:
    """Register a mode of a family: ``@mode("market", "auction", AuctionConfig, doc, example)``.

    ``example`` is the config without ``kind`` and ``mode``; ``was`` names the kind this mode replaces,
    so a contract still using it gets a clear error."""

    def register(expand: Callable[..., Dict[str, Any]]) -> Callable[..., Dict[str, Any]]:
        spec = FAMILIES.get(family_name)
        if spec is None:
            raise ValueError(f"mode '{mode}' names the unregistered family '{family_name}'")
        if mode in spec.modes:
            raise ValueError(f"mode '{family_name}.{mode}' is registered twice")
        for key in _SWITCH:
            if key in config.model_fields:
                raise ValueError(f"{family_name}.{mode}: a config cannot have a field named '{key}'")
        full_example = {"kind": family_name, "mode": mode, **(example or {})}
        spec.modes[mode] = ModeSpec(family_name, mode, doc, config, expand, full_example)
        spec.actions.setdefault(mode, {})
        if was is not None:
            RENAMED_KINDS[was] = (family_name, mode)
        return expand

    return register


def family_action(family_name: str, modes: Tuple[str, ...], action: str, *, example: str, keys: Tuple[str, ...] = (),
                  required: Tuple[str, ...] = (), literal: Tuple[str, ...] = (), templates: Tuple[str, ...] = (),
                  check: Optional[Callable[[Any, Dict[str, Any], str], list]] = None, binds: Tuple[str, ...] = (),
                  internal: bool = False, was: Tuple[str, ...] = ()) -> Callable[[Callable[..., None]], Callable[..., None]]:
    """Register one action of a family's op for some of its modes.

    ``{"<family>": <use name>, "action": "<action>", ...keys}``. ``run(runner, effect, vars, where)``
    reads the use name from ``effect[family]``. ``internal`` actions are generated by the mechanism
    itself (ticks, setup) and left out of the guide; ``was`` names the old ops it replaces."""

    def register(run: Callable[..., None]) -> Callable[..., None]:
        spec = FAMILIES.get(family_name)
        if spec is None:
            raise ValueError(f"action '{action}' names the unregistered family '{family_name}'")
        if action in ("", family_name) or "." in action:
            raise ValueError(f"'{action}' is not a valid action name")
        base = (family_name, "action")
        declared = (*base, *[k for k in keys if k not in base], *[k for k in binds if k not in keys])
        op = OpSpec(f"{family_name}.{action}", declared, run, example, tuple(required),
                    (*base, *literal), tuple(templates), check, tuple(binds), internal)
        for mode in modes:
            table = spec.actions.setdefault(mode, {})
            if action in table:
                raise ValueError(f"action '{action}' of {family_name}.{mode} is registered twice")
            table[action] = op
        for old in was:
            RENAMED_OPS[old] = (family_name, action)
        if family_name in OPS and OPS[family_name].select is None:
            raise ValueError(f"effect op '{family_name}' is registered outside its family; register it as a family action")
        OPS[family_name] = _family_op(spec)
        return run

    return register


# ---------------------------------------------------------------------------
# The family op: choosing the action an effect names
# ---------------------------------------------------------------------------


def _family_op(spec: FamilySpec) -> OpSpec:
    name = spec.name
    keys: List[str] = [name, "action"]
    for table in spec.actions.values():
        for op in table.values():
            keys.extend(k for k in op.keys if k not in keys)

    def select(effect: Mapping[str, Any], mechanisms: Mapping[str, Any]) -> Tuple[Optional[OpSpec], Optional[Issue3]]:
        use = effect.get(name)
        declared = uses_of(mechanisms, name)
        listing = ", ".join(declared) or "none"
        if not isinstance(use, str) or use not in declared:
            hint = get_close_matches(str(use), list(declared), n=1)
            fix = f"did you mean '{hint[0]}'?" if hint else (
                f"{name} mechanisms: {listing}" if declared else
                f"declare one: \"mechanisms\": {{\"my_{name}\": {{\"kind\": \"{name}\", \"mode\": ...}}}}")
            return None, (f".{name}", f"`{name}` names a declared {name} mechanism, got {use!r}", fix)
        mode = str(declared[use].get("mode"))
        table = spec.actions.get(mode, {})
        public = [a for a, op in table.items() if not op.internal] or list(table)
        action = effect.get("action")
        if not isinstance(action, str) or action not in table:
            hint = get_close_matches(str(action), list(table), n=1)
            what = "needs an `action`" if action is None else f"'{action}' is not an action of {use} ({name} {mode})"
            fix = f"did you mean '{hint[0]}'?" if hint else f"actions: {', '.join(public) or 'none'}"
            return None, (".action", what, fix)
        return table[action], None

    def run(runner: Any, effect: Dict[str, Any], vars: Dict[str, Any], where: str) -> None:
        from .errors import RunError  # imported late: errors imports nothing from here, but keep the registry import-light

        chosen, problem = select(effect, runner.world.contract.mechanisms or {})
        if problem is not None:
            raise RunError(f"{problem[1]}" + (f" — {problem[2]}" if problem[2] else ""), f"{where}{problem[0]}")
        assert chosen is not None
        missing = [key for key in chosen.required if key not in effect]
        if missing:
            raise RunError(f"`{name}` action '{effect['action']}' needs {', '.join(f'`{k}`' for k in missing)}", where)
        chosen.run(runner, effect, vars, where)

    example = f'{{"{name}": "<mechanism>", "action": "<action>", ...}}  (see guide("{name}"))'
    return replace(OpSpec(name, tuple(keys), run, example), literal=(name, "action"), select=select)


def renamed_op_hint(keys: Any) -> Optional[str]:
    """A fix for an effect written with an op that became a family action, or None."""
    for key in keys:
        found = RENAMED_OPS.get(key)
        if found is not None:
            family_name, action = found
            return (f"`{key}` is now the `{family_name}` op: {{\"{family_name}\": \"<mechanism>\", "
                    f"\"action\": \"{action}\", ...}}")
    return None
