"""Generate the reference docs from the installed SDK: one page per guide part, the Python API page, and the table of
example contracts in examples/README.md.

    python scripts/build_docs_reference.py           # regenerate (what `make docs` runs)
    python scripts/build_docs_reference.py --check   # exit 1 if a committed file differs (what `make check-docs` runs)
"""
from __future__ import annotations

import argparse
import inspect
import json
import re
import sys
from pathlib import Path
from typing import Any

import fg_env
from fg_env.guides import guide_parts

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "sdk"
EXAMPLES = ROOT / "examples"
CONTRACTS = EXAMPLES / "contracts"
TABLE_START = "<!-- contracts table: generated by scripts/build_docs_reference.py -->"
TABLE_END = "<!-- end contracts table -->"
#: A contract's summary in the examples table grows sentence by sentence until it is at least this long.
SUMMARY_CHARS = 60
ENV_METHODS = ["preview", "run", "arun", "step", "snapshot", "restore", "clone", "fork", "entity", "entities",
               "result", "spectate"]


def page_name(part: str) -> str:
    return f"reference-{part.replace('.', '-')}.md"


def reference_pages() -> dict[str, str]:
    """One page per guide part, and the index that lists them."""
    pages: dict[str, str] = {}
    index = ["# Contract reference", "",
             "Generated from the installed source models, expression registry and authoring guides. Regenerate with "
             "`make docs`.", "",
             "[Python API](api.md) · [Authoring workflow](authoring.md)", "", "## Guide sections", ""]
    for part in guide_parts():
        if part == "all":
            continue
        title = part.replace(".", " / ")
        pages[page_name(part)] = f"# {title}\n\n{fg_env.guide(part)}\n"
        index.append(f"- [{title}]({page_name(part)})")
    pages["reference.md"] = "\n".join(index) + "\n"
    return pages


def _is_public(obj: Any) -> bool:
    return inspect.isfunction(obj) or inspect.isclass(obj)


def _entry(heading: str, name: str, obj: Any) -> list[str]:
    lines = [f"{heading} `{name}`", ""]
    try:
        lines += ["```pyi", f"{name.rpartition('.')[2]}{inspect.signature(obj)}", "```", ""]
    except (ValueError, TypeError):
        pass
    doc = inspect.getdoc(obj)
    return lines + ([doc, ""] if doc else [])


def api_page() -> str:
    lines = ["# Python API reference", "",
             "Generated from public exports in `fg_env`. Start with `check`, `load`, `run` and `experiment`; "
             "everything else is in a subpackage below. A source may be a contract dictionary, JSON text, file path "
             "or parsed `Contract`.", "", "## Entry points", ""]
    exports = [(name, getattr(fg_env, name)) for name in fg_env.__all__]
    for name, obj in exports:
        if _is_public(obj):
            lines += _entry("##", name, obj)
    for name, module in exports:
        if not inspect.ismodule(module):
            continue
        lines += [f"## `fg_env.{name}`", "", inspect.getdoc(module) or "", ""]
        for export in module.__all__:
            obj = getattr(module, export)
            if _is_public(obj):
                lines += _entry("###", f"{name}.{export}", obj)
    lines += ["## Environment methods", ""]
    for name in ENV_METHODS:
        method = getattr(fg_env.Env, name)
        lines += [f"### `Env.{name}`", "", "```pyi", f"{name}{inspect.signature(method)}", "```", "",
                  inspect.getdoc(method) or "", ""]
    lines += ["## Detailed runtime behavior", "",
              "See [running](reference-running.md) for participants, budgets, traces, snapshots and experiments."]
    return "\n".join(lines) + "\n"


def example_contracts() -> list[Path]:
    """Every example contract. A folder named like a contract beside it (`exchange_flagship/`) holds that contract's
    imports and data, not examples of its own."""
    found = sorted(CONTRACTS.glob("*.json"))
    for folder in sorted(p for p in CONTRACTS.iterdir() if p.is_dir()):
        if not (CONTRACTS / f"{folder.name}.json").exists():
            found += sorted(folder.glob("*.json"))
    return found


def _summary(text: str) -> str:
    """The description's opening: its first sentence, and the next ones while that is too short to say much."""
    sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z])", text.strip())
    summary = sentences.pop(0)
    while sentences and len(summary) < SUMMARY_CHARS:
        summary += " " + sentences.pop(0)
    return summary


def examples_table() -> str:
    rows = ["| Contract | What it is |", "|---|---|"]
    missing = []
    for path in example_contracts():
        contract = json.loads(path.read_text(encoding="utf-8"))
        if not contract.get("description"):
            missing.append(str(path.relative_to(ROOT)))
            continue
        link = path.relative_to(EXAMPLES).as_posix()
        rows.append(f"| [`{path.relative_to(CONTRACTS).as_posix()}`]({link}) | **{contract['name']}.** "
                    f"{_summary(contract['description'])} |")
    if missing:
        sys.exit("give these example contracts a `description` (its opening goes in examples/README.md): "
                 + ", ".join(missing))
    return "\n".join(rows)


def examples_readme() -> str:
    text = (EXAMPLES / "README.md").read_text(encoding="utf-8")
    before, start, rest = text.partition(TABLE_START)
    _, end, after = rest.partition(TABLE_END)
    if not start or not end:
        sys.exit(f"examples/README.md must hold the markers {TABLE_START} and {TABLE_END}")
    return f"{before}{TABLE_START}\n{examples_table()}\n{TABLE_END}{after}"


def generated() -> dict[Path, str]:
    files = {DOCS / name: text for name, text in reference_pages().items()}
    files[DOCS / "api.md"] = api_page()
    files[EXAMPLES / "README.md"] = examples_readme()
    return files


def stale(files: dict[Path, str]) -> list[Path]:
    """Reference pages on disk that no guide part generates any more."""
    return sorted(p for p in DOCS.glob("reference-*.md") if p not in files)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report files that differ instead of writing them")
    args = parser.parse_args()
    files = generated()
    if args.check:
        changed = [p for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        problems = [*(f"differs: {p.relative_to(ROOT)}" for p in changed),
                    *(f"no longer generated: {p.relative_to(ROOT)}" for p in stale(files))]
        if problems:
            print("\n".join(problems), file=sys.stderr)
            print("The generated docs are out of date: run `make docs` and commit the result.", file=sys.stderr)
            return 1
        return 0
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")
    for path in stale(files):
        path.unlink()
    print(f"{len(files)} generated files written to docs/sdk and examples/README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
